# permissions for end users to edit kubearmorpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubearmorpolicy-editor-role
rules:
- apiGroups:
  - security.accuknox.com
  resources:
  - kubearmorpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - security.accuknox.com
  resources:
  - kubearmorpolicies/status
  verbs:
  - get
