apiVersion: security.accuknox.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-ubuntu-3-proc-dir-allow
  namespace: multiubuntu
spec:
  severity: 5
  selector:
    matchLabels:
      container: ubuntu-3
  process:
    matchDirectories:
    - dir: /bin/
  file:
    matchDirectories:
      - dir: /credentials/ # allow accessing the files in this directory; otherwise, deny all
        recursive: true
  action:
    AllowWithAudit
