apiVersion: security.accuknox.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-ubuntu-4-file-path-readonly-allow
  namespace: multiubuntu
spec:
  severity: 10
  selector:
    matchLabels:
      container: ubuntu-4
  process:
    matchDirectories:
      - dir: /bin/ # need some exectuables to test
  file:
    matchPaths:
    - path: /secret.txt # echo "test" >> /secret.txt (success)
      # fromSource:
      #   path: /bin/dash
    - path: /credentials/password # echo "test" >> /credentials/password (permission denied)
      readOnly: true
  action:
    Allow
